version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: jedwal-dynamodb
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
